---

  - name: build-essentials
    yum: name={{item}} state=installed
    with_items:
      - autoconf
      - gcc
      - bison
      - flex
      - gcc-c++
      - gettext
      - kernel-devel
      - make
      - m4
      - ncurses-devel

  - name: install couchdb
    include: 'couchdb.yml'
